### ISSUE TITLE
More responsive engaging of combat mode when centering mouse

### ISSUE THREAD

**Issue by Jaerin** [Xuerian/Lockdown#44]
I know we are bound by using the cursor clipping to have AHK detect when it should rebind the mouse buttons.  Just trying to think about how we might sync up the enter combat mode key press a little more closely with when things lock.

The slight stutter that AHK does to recenter the mouse feels a bit messy.  Not sure what we can do with this.

**Comment by Xuerian** [comment]
There isn't anything I can think of off the top of my head. You can try lowering the delays, but I also ran into the problem earlier that the cursor flickers in the game now, especially when mousing over some frames - if your FPS is low enough, it can be long enough that MouselockRebind picks it up as a lock and centers.

**Comment by Xuerian** [comment]
The bad part is I'm going to have to make it worse due to the above, I think. 

The only practical solution that occurred to me is to only assume the cursor is locked if it appears locked for multiple sequential checks.
