### ISSUE TITLE
Offset not accurate 

### ISSUE THREAD

**Issue by decoytrix** [Xuerian/Lockdown#45]
Seems that the visual for the reticle moves when offset is adjusted, but the targeting spot itself doesn't actually mode at all. If I move the offset up, I have to aim above what I want to target. 

Sometime after a relog it seems to be working.  Occasionally it will also target units in the modified position as well as the default position, causing conflicts when a unit is over another.

**Comment by Xuerian** [comment]
The mouseover or Lockdown's actual targeting area? Lockdown only targets stuff inside the reticle (And in a circle, not a square, actually). The mouseover location can sometimes cause issues, as it is stuck dead in the middle of the screen. We can't move it. 

That said, if you still think it's Lockdown I can definitely look into it.

**Comment by decoytrix** [comment]
Did a little more testing.  If I offset completely to one side, any enemies to fall into the offset position autotarget perfectly.  Anything that is not an enemy will not register.  So basically the reticle cannot be used to target friendly NPCs/players or any use items like terminals and buff stations.  The center default position still existed for use in targeting these non-enemies, so I would essentially have two reticles, one invisible in the center default space and my Lockdown one at its offset for use on enemies.

**Comment by Xuerian** [comment]
Yeah. To be blunt, that's Carbine's fault.

Lockdown manually scans for targets close to the crosshair and targets them.

It can't move the cursor location - the thing that sits in the middle of your screen and takes priority for object interactions.

Carbine needs to add settings for mouseover and camera positions. Unfortunately it seems like it is very low priority for them, even though the control scheme makes the game much more playable.

See: (Also a thread I made at original launch that has now been deleted, apparently)

https://forums.wildstar-online.com/forums/index.php?/topic/131228-automatic-mouse-look-feedback/
https://forums.wildstar-online.com/forums/index.php?/topic/142982-proper-mouselook-please/
https://forums.wildstar-online.com/forums/index.php?/topic/142850-automatic-mouse-look-beta-cursor-re-center

**Comment by decoytrix** [comment]
Thanks for letting me pick your brain then.  
Do you know if it is possible to move the camera position?  Maybe if it is raised some, my crosshair wouldn't be embedded in the back of my character's neck.

**Comment by Xuerian** [comment]
It is not, unfortunately. See the first thread.

That's why I've been asking for this for a while, and that's why Lockdown's targeting does what it does.

It helps, sort of. It's not perfect.

**Comment by decoytrix** [comment]
Apologies, I should have read those before I commented, I see the thread you made.  Thanks for the links.

**Comment by Xuerian** [comment]
/bug it, post a feedback thread, something. More squeaky wheels, more grease.

Let me know if you have any other Lockdown feedback if you end up using it.
